### ISSUE TITLE
Enable all games

### ISSUE THREAD

**Issue by Tomin1** [Tomin1/patience-deck#1]
Enable all games from GNOME Aisleriot and get rid of allowlist in GameList class.

**Comment by poetaster** [comment]
That is a great idea :)

I wanted to add a really far flung idea. Some of the games, like Isabel, are simple matching games. With a set of 'cards' that are mahhong tiles (let's say 52 cards/stones suffices) you could easily implement mahjong like tile games. 

I've forked but just realized you're using the platform SDK and I'm doing all my projects in the Application SDK...

**Comment by Tomin1** [comment]
> That is a great idea :)

Heh, well, I really wanted to put something meaningful and important to #1 before someone else happens to file a bug. :grin: 

> I wanted to add a really far flung idea. Some of the games, like Isabel, are simple matching games. With a set of 'cards' that are mahhong tiles (let's say 52 cards/stones suffices) you could easily implement mahjong like tile games.

Sounds like a great idea. I think the engine should be quite suitable for that. Just replace the card texture svg with a mahjong tile texture svg. Tweaking the code in card.cpp and enginedata.cpp should allow you to define any set of tiles so you are not limited to the 55 different "tiles" or the shape that Patience Deck has (patience games are not limited to that number of cards, they can use cards from multiple decks if they like). It's probably possible to use slots so that they can make up most of the different mahjong layouts. Some of the slots need to overlap but some patience games do that so it's not an issue as such.

> I've forked but just realized you're using the platform SDK and I'm doing all my projects in the Application SDK...

I think you can build it on Application SDK anyway but I haven't made any instructions for that. You may need to ssh to the build engine VM (or do whatever docker requires you to do to get command line) to build the support libraries inside that ([see also this command for building those](https://sailfishos.org/wiki/Building_packages#Dumb_packages)). It might be also that [sfdk](https://sailfishos.org/wiki/Application_Development#sfdk_command_line_tool) is capable enough to build these but I haven't tried that.

I have planned to include building support libraries in the main spec and bundling them to the package but I haven't yet got that far. After that it's probably almost trivial to support Application SDK. First I need to build a scheme library (= guile) that could be accepted in Harbour as currently it has some dependencies I just can't bundle but slimming it down would be a good idea anyway. In any case I should probably improve those build instructions, they are quite terse at the moment. :smiley:

**Comment by poetaster** [comment]
I'm going to tinker with:
1. An svg that's suitable. Which basis: data/anglo.svg?
2. A test with, Isabel, 'as is'
3. A test with Isabel, modified layout.

I think this can all be done without changing the engine at all ... .There appear to be 42 standard tiles. Of these for any game there are generally 2 pairs.

But I'll get to the sdk at some point (too many projects!)

**Comment by Tomin1** [comment]
> I'm going to tinker with:
> 
>     1. An svg that's suitable. Which basis: data/anglo.svg?

Anglo.svg definitely. Or pick some other one from aisleriot/cards (remember to check the license though, [anglo.svg is GPLv3+ or so](https://bugzilla.gnome.org/show_bug.cgi?id=461267#c8) but there may be other licenses as well).

> But I'll get to the sdk at some point (too many projects!)

Sure. Also there is probably some more suitable forum to discuss the subject instead of hijacking this issue. :smiley:

**Comment by poetaster** [comment]
Am on it. A better forum, good question.  Let me know where. This works, oddly ;) https://github.com/poetaster/patience-deck/blob/master/data/mahjong.svg   and the obligatory screen: https://github.com/poetaster/patience-deck/blob/master/data/20210425152300.png

**Comment by Tomin1** [comment]
This has been released in Patience Deck 1.0. All games are now supported!

Btw, in future, if someone wants to ask questions about or discuss Patience Deck privately, then just send [me](https://forum.sailfishos.org/u/tomin/summary) a direct message on Sailfish OS forum. It works well for that purpose too.

**Comment by poetaster** [comment]
Cool and Thanks! Now we have even more scheme files to worry our way through!
